/*
 * smbus.h
 *
 * Created: 4/29/2021 6:43:02 PM
 *  Author: E1210640
 */ 


#ifndef SMBUS_H_
#define SMBUS_H_

#define SMBUS_CMD_GET_STATUS				0xF0
#define SMBUS_CMD_UPGRADE_START				0XF1
#define SMBUS_CMD_UPGRADE_SEND_DATA			0XF2
#define SMBUS_CMD_UPGRADE_ACTIVATE			0XF3

#define SMBUS_STATUS_BUSY					(1 << 0)
#define SMBUS_STATUS_PEC_ERROR				(1 << 1)
#define SMBUS_STATUS_UPGRADE_ERROR			(1 << 2)

#define SMBUS_REG__5VAUX_LOW_BYTE			0x00
#define SMBUS_REG__5VAUX_HIGH_BYTE			0x01
#define SMBUS_REG__3V3_LOW_BYTE				0x02
#define SMBUS_REG__3V3_HIGH_BYTE			0x03
#define SMBUS_REG__5V_LOW_BYTE				0x04
#define SMBUS_REG__5V_HIGH_BYTE				0x05
#define SMBUS_REG__12V_LOW_BYTE				0x06
#define SMBUS_REG__12V_HIGH_BYTE			0x07
#define SMBUS_REG__M12V_LOW_BYTE			0x08
#define SMBUS_REG__M12V_HIGH_BYTE			0x09

#define SMBUS_REG__SEL_SS_PS_ON				0x0E
#define SMBUS_REG__SS_PS_ON_IN				0x0F
#define SMBUS_REG__EXT_PS_ON_IN				0x10
#define SMBUS_REG__PS_ON_OUT_1				0x11
#define SMBUS_REG__PS_ON_OUT_2				0x12
#define SMBUS_REG__PS_ON_OUT_3				0x13
#define SMBUS_REG__PS_ON_OUT_4				0x14
#define SMBUS_REG__AC_OK					0x15
#define SMBUS_REG__PWR_OK					0x16
#define SMBUS_REG__REMOTE					0x19 //write
#define SMBUS_REG__SET_FAN					0x1A //write
#define SMBUS_REG__FAN_CURVE				0x1B //write + ENV
#define SMBUS_REG__FAN_TACHO_1_LOW_BYTE		0x1C
#define SMBUS_REG__FAN_TACHO_1_HIGH_BYTE	0x1D
#define SMBUS_REG__FAN_TACHO_2_LOW_BYTE		0x1E
#define SMBUS_REG__FAN_TACHO_2_HIGH_BYTE	0x1F
#define SMBUS_REG__FAN_TACHO_3_LOW_BYTE		0x20
#define SMBUS_REG__FAN_TACHO_3_HIGH_BYTE	0x21
#define SMBUS_REG__FAN_TACHO_4_LOW_BYTE		0x22
#define SMBUS_REG__FAN_TACHO_4_HIGH_BYTE	0x23
#define SMBUS_REG__FAN_TACHO_5_LOW_BYTE		0x24
#define SMBUS_REG__FAN_TACHO_5_HIGH_BYTE	0x25
#define SMBUS_REG__FAN_TACHO_6_LOW_BYTE		0x26
#define SMBUS_REG__FAN_TACHO_6_HIGH_BYTE	0x27
#define SMBUS_REG__FAN_UNIT_READY			0x28
#define SMBUS_REG__FAN_FAIL					0x29
#define SMBUS_REG__FAN_SPEED				0x2A

#define SMBUS_REG__TEMP_AIR_INLET			0x2C
#define SMBUS_REG__TEMP_AIR_OUTLET1			0x2D
#define SMBUS_REG__TEMP_AIR_OUTLET2			0x2E
#define SMBUS_REG__TEMP_AIR_OUTLET3			0x2F
#define SMBUS_REG__TEMP_AIR_OUTLET4			0x30
#define SMBUS_REG__TEMP_FAIL				0x31

#define SMBUS_REG__TBPRES					0x34
#define SMBUS_REG__TB1_EN					0x35 //write + ENV
#define SMBUS_REG__TB1_DIR					0x36 //write + ENV
#define SMBUS_REG__TB2_EN					0x37 //write + ENV
#define SMBUS_REG__TB2_DIR					0x38 //write + ENV
#define SMBUS_REG__TB3_EN					0x39 //write + ENV
#define SMBUS_REG__TB3_DIR					0x3A //write + ENV
#define SMBUS_REG__TB4_EN					0x3B //write + ENV
#define SMBUS_REG__TB4_DIR					0x3C //write + ENV

#define SMBUS_REG__ADD_LOW_BYTE				0x41 //write
#define SMBUS_REG__ADD_HIGH_BYTE			0x42 //write
#define SMBUS_REG__DATA						0x43 //write
#define SMBUS_REG__WRITE_DATA				0x44 //write
#define SMBUS_REG__CLOCKMODUL_PRESENT		0x45
#define SMBUS_REG__SYNC100_DIV				0x46 //write
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_1	0x47
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_2	0x48
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_3	0x49
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_4	0x4A
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_5	0x4B
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_6	0x4C
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_7	0x4D
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_8	0x4E
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_9	0x4F
#define SMBUS_REG__CLOCK_MODULE_FW_BYTE_10	0x50

#define SMBUS_REG__CONFIG					0x55
#define SMBUS_REG__MAX_SPEED				0x56

#define SMBUS_REG__CMM_FW_BYTE_1			0x60
#define SMBUS_REG__CMM_FW_BYTE_2			0x61
#define SMBUS_REG__CMM_FW_BYTE_3			0x62
#define SMBUS_REG__CMM_FW_BYTE_4			0x63
#define SMBUS_REG__CMM_FW_BYTE_5			0x64
#define SMBUS_REG__CMM_FW_BYTE_6			0x65
#define SMBUS_REG__CMM_FW_BYTE_7			0x66
#define SMBUS_REG__CMM_FW_BYTE_8			0x67
#define SMBUS_REG__CMM_FW_BYTE_9			0x68
#define SMBUS_REG__CMM_FW_BYTE_10			0x69
#define SMBUS_REG__CMM_VERSION				0x6A

#define SMBUS_REG__CMM_PDB_TEMP_1					0x71
#define SMBUS_REG__CMM_PDB_TEMP_2					0x72
#define SMBUS_REG__CMM_PDB_POWER_3V3_LOW_BYTE		0x73
#define SMBUS_REG__CMM_PDB_POWER_3V3_HIGH_BYTE		0x74
#define SMBUS_REG__CMM_PDB_MAX_POWER_3V3_LOW_BYTE	0x75
#define SMBUS_REG__CMM_PDB_MAX_POWER_3V3_HIGH_BYTE	0x76
#define SMBUS_REG__CMM_PDB_POWER_5V_LOW_BYTE		0x77
#define SMBUS_REG__CMM_PDB_POWER_5V_HIGH_BYTE		0x78
#define SMBUS_REG__CMM_PDB_MAX_POWER_5V_LOW_BYTE	0x79
#define SMBUS_REG__CMM_PDB_MAX_POWER_5V_HIGH_BYTE	0x7A
#define SMBUS_REG__CMM_PDB_POWER_12V_LOW_BYTE		0x7B
#define SMBUS_REG__CMM_PDB_POWER_12V_HIGH_BYTE		0x7C
#define SMBUS_REG__CMM_PDB_MAX_POWER_12V_LOW_BYTE	0x7D
#define SMBUS_REG__CMM_PDB_MAX_POWER_12V_HIGH_BYTE	0x7E
#define SMBUS_REG__CMM_PDB_MAX_POWER_TOTAL_LOW_BYTE 0x7F
#define SMBUS_REG__CMM_PDB_MAX_POWER_TOTAL_HIGH_BYTE 0x80
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_1		0x81
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_2		0x82
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_3		0x83
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_4		0x84
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_5		0x85
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_6		0x86
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_7		0x87
#define SMBUS_REG__CMM_PDB_PRODUCT_NUM_Byte_8		0x88
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_1		0x89
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_2		0x8A
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_3		0x8B
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_4		0x8C
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_5		0x8D
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_6		0x8E
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_7		0x8F
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_8		0x90
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_9		0x91
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_10		0x92
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_11		0x93
#define SMBUS_REG__CMM_PDB_SERIAL_NUM_Byte_12		0x94

uint8_t smbus_get_input_reg(uint8_t nr);
void smbus_set_input_reg(uint8_t nr, uint8_t val);
void smbus_init(void);
void do_smbus(void);

#endif /* SMBUS_H_ */